# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Removes a functional object from the list. 
#'
#' Returns true if member awas on the list, returns false otherwise. 
#'
removeMember <- function(address) {
    .Call(`_fctbases_removeMember`, address)
}

getObjectsOnList <- function() {
    .Call(`_fctbases_getObjectsOnList`)
}

init_bspline <- function(spline_order, spline_knots) {
    .Call(`_fctbases_init_bspline`, spline_order, spline_knots)
}

cpp_eval_coefs <- function(address, x, coefs, check_valid = TRUE) {
    .Call(`_fctbases_cpp_eval_coefs`, address, x, coefs, check_valid)
}

cpp_eval_0 <- function(address, x, check_valid = TRUE) {
    .Call(`_fctbases_cpp_eval_0`, address, x, check_valid)
}

cpp_eval_Dcoefs <- function(address, x, coefs, check_valid = TRUE) {
    .Call(`_fctbases_cpp_eval_Dcoefs`, address, x, coefs, check_valid)
}

cpp_eval_D <- function(address, x, check_valid = TRUE) {
    .Call(`_fctbases_cpp_eval_D`, address, x, check_valid)
}

#'
#' Init fouriter basis
#' @param range
#' @param order
#' @param trig_basis Currently ignored.
#'
init_fourier_basis <- function(range, order, trig_basis = FALSE) {
    .Call(`_fctbases_init_fourier_basis`, range, order, trig_basis)
}

init_pol_basis <- function(pol_order, ptype = FALSE) {
    .Call(`_fctbases_init_pol_basis`, pol_order, ptype)
}

