# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'  Initialize uniform B-spline
#'
#' Initilaises a uniform b-spline.
#'
#' @param spline_order order = degree + 1
#' @param range Left and right end points.
#' @param nknots No. of knots including end points
#' @export
#' 
init_unif_bspline <- function(range, nknots, spline_order, ind_count = FALSE) {
    .Call('Functional_init_unif_bspline', PACKAGE = 'Functional', range, nknots, spline_order, ind_count)
}

#'  Initialize B-spline
#'
#' Initialises b-spline and returns address.
#'
#' @param spline_order order = degree + 1
#' @param spline_knots Knots of the b-spline, including endpoints. Must be increasing.
#' @export
#' @return integer.
#' @useDynLib Functional
initBspline <- function(spline_order, spline_knots, ind_count = FALSE) {
    .Call('Functional_initBspline', PACKAGE = 'Functional', spline_order, spline_knots, ind_count)
}

initBspline1 <- function(spline_knots, ind_count = FALSE) {
    .Call('Functional_initBspline1', PACKAGE = 'Functional', spline_knots, ind_count)
}

#'  Initialize Fourier basis
#'
#' Assign value to the global b-spline.
#'
#' @param spline_order order = degree + 1
#' @param range Left and right end points.
#' @param nknots No. of knots including end points
#' @export
#' @useDynLib Functional
init_fourier_basis <- function(range, f_order, j = FALSE) {
    .Call('Functional_init_fourier_basis', PACKAGE = 'Functional', range, f_order, j)
}

#'  Polynomial basis
#'
#' Makes a polynomial basis
#'
#' @param deg Polymoial degree
#' @export
#'@importFrom Rcpp sourceCpp
#' 
init_pol_basis <- function(deg) {
    .Call('Functional_init_pol_basis', PACKAGE = 'Functional', deg)
}

#' getObjectsOnList()
#' 
#' Get addresses of current objects
#'
#'
#'@export
#'@return A list of addresses.
#'@useDynLib Functional
#'@importFrom Rcpp evalCpp
#'
getObjectsOnList <- function() {
    .Call('Functional_getObjectsOnList', PACKAGE = 'Functional')
}

#' Empty list
#'
#' Empties the entire container of functional objects. Does not delete R objects
#' 
#' @export
#' @useDynLib Functional
#' @seealso removeMember
#'
emptyList <- function() {
    invisible(.Call('Functional_emptyList', PACKAGE = 'Functional'))
}

#' Remove member
#'
#' Deletes specified member from the memory.
#' 
#' @export
#' @useDynLib Functional
#'
removeMember <- function(address) {
    .Call('Functional_removeMember', PACKAGE = 'Functional', address)
}

cpp_eval_coefs <- function(address, x, coefs) {
    .Call('Functional_cpp_eval_coefs', PACKAGE = 'Functional', address, x, coefs)
}

cpp_eval_0 <- function(address, x) {
    .Call('Functional_cpp_eval_0', PACKAGE = 'Functional', address, x)
}

cpp_eval_Dcoefs <- function(address, x, coefs) {
    .Call('Functional_cpp_eval_Dcoefs', PACKAGE = 'Functional', address, x, coefs)
}

cpp_eval_D <- function(address, x) {
    .Call('Functional_cpp_eval_D', PACKAGE = 'Functional', address, x)
}

#'  Check if valid
#'
#' Check if address is valid
#'
#' @param address
#' @export
#' @useDynLib Functional
check_if_valid <- function(address) {
    .Call('Functional_check_if_valid', PACKAGE = 'Functional', address)
}

